apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgrest-app
  template:
    metadata:
      labels:
        app: postgrest-app
    spec:
      containers:
      - name: postgrest
        image: postgrest/postgrest:latest
        env:
        - name: PGRST_DB_URI
          value: postgres://username:password@postgres-service:5432/postgres
        - name: PGRST_DB_SCHEMA
          value: public
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: postgrest-service
spec:
  selector:
    app: postgrest-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
